### ISSUE TITLE
Hourly data not available

### ISSUE THREAD

**Issue by raixer** [dotKrad/hass-fpl#67]
Hourly data is always Unknown even with the latest update.

**Comment by raixer** [comment]
For anyone who finds this useful: I found out that the Hourly data entity is always unknown because that is the current state. You don’t get data of the current date, only the date before and that is tracked by a separate hidden entity. When you go to the energy dashboard configuration, choose that hidden entity instead and that will contain the hourly data for the day before and prior. 

My only problem now is that there is a gap everyday where the information is missing for hours 8, 9, and 10 pm.

**Comment by CamiloValderruten** [comment]
Hi @raixer,

Glad you were able to find that information. I'll update the README with instruction to setup the Energy Dashboard. 

In one of the latest versions, I though I had fixed that missing hours bug, but guess not. I'll take a look at it this week :)

**Comment by FlyersPh9** [comment]
> I'll update the README with instruction to setup the Energy Dashboard.

Very interested in this as well.

**Comment by donincognito22** [comment]
I have the same issue regarding missing data for the evening hours.

**Comment by FlyersPh9** [comment]
I figured it out this weekend.  In the screenshot it shows 2 entities.  The first one with the ⚡️ icon is **not** the one you want to pick, you want to pick the one with the 📈 icon.

<img width="412" height="362" alt="Image" src="https://github.com/user-attachments/assets/fdf260f4-9802-47ac-8f12-706438dcd900" />

**Comment by YaannnTech** [comment]
> I have the same issue regarding missing data for the evening hours.

I have that issue as well. I get hourly data from midnight to 8:00pm, and then nothing for the last four hours of the day. And I'm using the entity that @FlyersPh9 pointed out in his post directly above this one. This is for FPL in South Florida.

<img width="1314" height="403" alt="Image" src="https://github.com/user-attachments/assets/bd78509a-3320-4112-aa84-5ed6f3fbacfe" />

**Comment by YaannnTech** [comment]
I fixed the issue with the missing four hours of hourly usage. This required only a single line to be changed. 

I created a pull request here: https://github.com/dotKrad/hass-fpl/pull/71

@dotKrad 

<img width="1166" height="495" alt="Image" src="https://github.com/user-attachments/assets/2b583c8a-6e16-49d2-982e-9648cc219595" />

**Comment by YaannnTech** [comment]
My apologies, my fix didn't work in the current 2026.x HA environment. I was fooled into believing it worked in the dev environment.

**Comment by CamiloValderruten** [comment]
Fixed in **v1.0.2** and **v1.0.3**.

**Root causes (there were several):**

1. **Hourly backfill crash (v1.0.2, #76)** — `mobile-hourly-usage` returns `HourlyUsage` as a top-level array, not `{ "data": [...] }`. That prevented hourly statistics from being published at all.

2. **Wrong entity in Energy Dashboard** — The ⚡ *Hourly Usage KWH* / *Hourly Cost* **sensors** stay `unknown` by design (they are debug-only). The Energy Dashboard needs the 📈 **external statistics**:
   - `fpl:<account>_hourly_usage`
   - `fpl:<account>_hourly_cost`

   README now documents this under **Energy Dashboard**.

3. **“Missing” 8–10 PM hours** — Not an API or timezone bug. FPL returns all 24 hours (confirmed via mitmproxy on `mobile-energy-service` and `mobile-hourly-usage`). Bad **stale recorder rows** (zeros) from an old backfill were the issue. Clearing those statistics and letting the integration re-backfill 15 days restores correct evening data.

**What to do on upgrade:** Update to v1.0.3 via HACS, configure Energy Dashboard with the statistics entities above, and if evening hours still look wrong, clear the `fpl:*_hourly_usage` / `*_hourly_cost` statistics once (Developer Tools → Statistics) and restart HA to trigger a fresh backfill.

**Comment by donincognito22** [comment]
Clearing the statistics will backfill the missing evening hours, but they still do not show in the Energy Dashboard for subsequent days.
